l1Config:
    networkConfig: 0x6d6C50215847E7AA38BF95403F008F23081e0e4B
    messagebus: 0x58f890421B7cD41931cd4E1578De9544afB58eEf
    bridge: 0x842B7C1b41d47e38fDD9d586455350A1D4eA2264
    crosschain: 0xE359AA678a7524c1EbC9dE5cF200e5e57206fab5
    rollup: 0xfdcF49cE577084c3258260540211FBd20e28BD27
    enclaveRegistry: 0x9c54898eFb550e1e6327f9aCF7DAb28a56CC7CEb
    starthash: 0x2c351ef11a7ea479a7881b13e65b2d1bec7029c509b80299d8e8a28609c731b9
