l1Config:
    networkConfig: 0x1d72a5BE8B2f92CB0453B7d47bc9353C71FDe098
    messagebus: 0xCc03f0357484D26C3024B5121a2d99c457cFCAb8
    bridge: 0xc9DD8f27B862Ab0b87057cC7Bf2433880d213440
    crosschain: 0x40FF4fDA3AEcD71C0D508556E52305aCBf1E3eF8
    rollup: 0xD8CBB7fd2481E8E7D19eF5E13F4Dc177978C8eAe
    enclaveRegistry: 0x003a56a91b9142114570715d6fB25f6218a9E616
    starthash: 0x52333235593077d26e513a6903aea6f6cd4103531bb864fe826e8615dad16b7f
