l1Config:
    networkConfig: 0x1BE479810c5cD7684AF6Df8EBf0059963462A051
    messagebus: 0xf692358639Fed2eCC921AB809015e2aF495A1F51
    bridge: 0x6E2F5BAAe3e3d0752Fea6aA1e46F13956D5622C9
    crosschain: 0xE69F1130C257E8f78BadeF05d48b05e98EffE6C9
    rollup: 0xAa3ca888483A8e907721D1d8868dFF86dbC3DE45
    enclaveRegistry: 0x303F47c0F07aEdeeAFA2E230A62ADa7aD0f8ABDC
    starthash: 0x4569735df14773863029667388860fa42ecbe8cc09ff2c6b82b41329482e601b
