l1Config:
    networkConfig: 0x163514aD2AfC02C707D7AeB79D9bF2f0118A1CE7
    messagebus: 0xF5EF62c9AbDB44C07493f3B052879B8Cc480aBDC
    bridge: 0x612b57b6FC077C990e29A9748D2d20FB7994B132
    crosschain: 0x83B3323C33a014F287Ee82cd836565064De76828
    rollup: 0x46e4F88CB3e97d9211AdAE5A7c00f9524fE9EC13
    enclaveRegistry: 0x494883F9660196103E9c594Dd45Fe51CfC18c443
    starthash: 0x8631b3193418457c67fd908049a66f1a3c06d16146525cbbf96f03cbc3204c97
