l1Config:
    networkConfig: 0xAF143b353216694d84efA8c6A0986c32063130c4
    messagebus: 0x823B53C116285B59E89178cFD256eFcB3AC66d0D
    bridge: 0x6B2E619f7f492A2d92c27Fbd9d181BE7cb0Ce12D
    crosschain: 0xD717a8a36dE820EC65797AC9BEd6Ef3A1989B504
    rollup: 0x8606D78510173b92a3C44CFC06Fe67e75B581739
    enclaveRegistry: 0x5A5C04Cf83b91c8d746B0933a6Cd4E2A03cCb5bc
    starthash: 0x794b50618bb6278ef089f5f18bb9e8b36da662cb620f3f2ec6e6380fe439722e
