l1Config:
    networkConfig: 0x7bfAD068fca26A2c78BEF1fFAd2D6eB62cfB5A89
    messagebus: 0xCa615a6d57370d5B3EC5433b2f546f23C67D9A6e
    bridge: 0xD9c1D8b7bf74E99b1F7117ce4c1680a792746b6C
    crosschain: 0x54Bd399f5C9110371eaD89C60BC574022C6eF007
    rollup: 0x8301054F42635d9Cf8D82Fb1B8f9Ef8036960F8D
    enclaveRegistry: 0x404AB3436b906547dC8257B07D1A2Ce8cBdA7B26
    starthash: 0x4cae861bffcf857946c076ddba1045ed2b6c80533af7c464070ab0fbc4f997d7
