l1Config:
    networkConfig: 0xE34801Ceb3c9fCdEff3f8858a5434Ab94a468F76
    messagebus: 0x75c1214A947A42723c4dbC6fcfcF756c7EA57Ae2
    bridge: 0x8C75c5a7BDe6d9E26dD27Da4a423d975521036E5
    crosschain: 0x794642820FD52396388EB8Cb32282e366999fe3e
    rollup: 0x2FC551803aFA2b54331eE47cC35B4F6511Fa9258
    enclaveRegistry: 0x6f7eFfEC51930c48C2caFD6B78d9cE49859Dcc3d
    starthash: 0x4016711f75a26e3ef13180e14b903d6ae2b3f8651f31ca851f70bb53d015dc28
