l1Config:
    networkConfig: 0xe14348F9026b42CFb4fBdD8eF5626b9Fda9489Ff
    messagebus: 0xe3D226D158063b8cb9d9661A51d673DD0CadbC02
    bridge: 0x666bd98A3F7d5bc3ED4f9dd8DFc33197e2cA23C1
    crosschain: 0xCae7dab829cae727DF65e4ef5216212e3bF91435
    rollup: 0x2E500bDf878eE0edc787bCb235cf9097f4D9fD43
    enclaveRegistry: 0xe3430f021161695B6156cfc4307E2D709A0c09CB
    starthash: 0x9a6e014442e3c4fc49a1d065330758cd611de9aaa0dbef8bf59a7aceb6645662
