l1Config:
    networkConfig: 0x32Dbd5DE5515370FeA5bB88a918e871b28d9F2FB
    messagebus: 0x5f4C79835cB4134164484569D7c2966e43fD4F5F
    bridge: 0xd9FFd5E211Fb63a53c85A1c1f3D2a6066FD22cdb
    crosschain: 0xC82F48d7C2793d69C35B1703D481Af2EFdcdD400
    rollup: 0x780bE3D29Ba49ccF36D983A5ba46de07A80c8b3e
    enclaveRegistry: 0x6c148b4C991c5c73bb18Cc238c9835C01166Dc72
    starthash: 0x34a835f4fd733641998245c65a47ab1306f2f97fa19405f50589f44be4f234db
