l1Config:
    networkConfig: 0xb309DDD55dBb720AFB6a54F75818e5F8dc982211
    messagebus: 0x485dBD940633E2fc596c0E93259CCb0e18c5aC47
    bridge: 0xBEA8B4690EF1fe4EC166dc9E6480F95e7de65155
    crosschain: 0xB86156b89A098AEDDB364e300617d18dd4E1E80C
    rollup: 0xe0FD48984383feee77bbb264777542aD1b64A661
    enclaveRegistry: 0xD38E025afF4b380ae3391826Fbdd73A3BB6C2055
    starthash: 0x4826234ebbdfdc4efc0386ca3cfb215cad9e75fbdede02b39f71b3e7abb2f903
