l1Config:
    networkConfig: 0xeEDa1FfC23Cc6Aae926fad2d196dfE017dd15200
    messagebus: 0x0C21e8eC89B08A1043A6bD5482478cb3B01B0bad
    bridge: 0x269339613DBA810F31184A19DcbbDc768Ec6152e
    crosschain: 0xa37aB6767A40130728ADe1d37dbA81f06889068E
    rollup: 0x2946116543e5654b6AC0795AcA5f88c28d607900
    enclaveRegistry: 0xBA27B35C26DAD9CfA1c777cE28135970f3900728
    starthash: 0x20e90b6f6c515b67b9f2e1afc88e277c4eef6b3a4ae45a71ac89472e84904571
