l1Config:
    networkConfig: 0xf568D120E46a25C510E47349871292Ac16A6a44d
    messagebus: 0x6d43e6Be45d0c3a27E21FAab2F4D6EAf498d5a39
    bridge: 0xE15654477bfEb8a3227122A6Aa69773d8c9fe139
    crosschain: 0xf3e97191E3554D159a401E97DBe20d5F693749F9
    rollup: 0x9010531B2fe9f415a2Ab50AFddB4A371CB1f1C6F
    enclaveRegistry: 0xfa7005c5726d3DF0669B609bb2307A544Ce7eC8E
    starthash: 0x2a5c475157b3c03885ab0b1c92fff53d63dca6b598131a1d57151ef14eb1df2e
