l1Config:
    networkConfig: 0xFB590BF352F05Ac14f3100139d733600E1b0fB44
    messagebus: 0x5D5bc9d7a117D173784CC1F4d1dd7EFC6846409F
    bridge: 0x2Becd707E793c8a5378a6292B8d119df257b25F1
    crosschain: 0x3A79F18B4783cc331Dd0111230Aaf91c94E86e24
    rollup: 0x0757ca15702047825179D39a0c1c00361E4bDA92
    enclaveRegistry: 0x3afc27fAea2F2715dcc8F9bdC7711C94a9Ad76a5
    starthash: 0x5e3ed10b60dfecdd2bbbe015d42706c98437bb72649596f297cadf21f6ef7120
