l1Config:
    networkConfig: 0xAFcaAaa38299757A019f124dDEc42fF6F2073448
    messagebus: 0x4793E7fE482A0d3756B340eF83271e27C8800068
    bridge: 0x245ea4fd6ecd254D799f2e14ACf85Ab592E7BDd7
    crosschain: 0x3Ec11C8D41D42594Ad809058B70829Fde605ab50
    rollup: 0x69d943802251B061E4aaBC65D925FE8D70136A18
    enclaveRegistry: 0x8C6d32C6Dc3547ef070814340066E45Fd57c248C
    starthash: 0x85b8bb01352ae19c1a5cc631ce8393906455e196011315da43b0b088979ff795
