l1Config:
    networkConfig: 0x6f792Fe85Ce80b19C4A36BB693E1530b54AE9000
    messagebus: 0x9AD330c30C1E97f7ed5d23b9A498EEbB461FB433
    bridge: 0xD4F310CBa3D04B74582c0D010a8A0388D56bfacf
    crosschain: 0xa4180Ab9c000Aa254b9728F4605A90dB2ccF5Bc8
    rollup: 0x8b8C95CC57FDCCa6A4A4f98E9Afed182A533B1Fe
    enclaveRegistry: 0x587C74398e11003C087819A2eF642D6c66B455F5
    starthash: 0x7e12c3a988f6571076ecc039cef296f1e5d5d6271b053d75273deeccf8276af1
