l1Config:
    networkConfig: 0x1D055fd30927085993b57Bc64A1896c3a214F507
    messagebus: 0x089155b81af19de39E498aEb5561D42500A99106
    bridge: 0x80F86787e0C75FEEe098Ffa9D37Aa55D333cd6A1
    crosschain: 0x29E12Cb4f8AeA5B0f467A77Fa12171A2a2D7C761
    rollup: 0x8E17C62E2653a307552de342695E3230c1d847Cf
    enclaveRegistry: 0x8AEDE27E443E9AA69EDA1D0402E6b5aa2738fCcf
    starthash: 0x949dca6d1a16c68f638aee2d15bce52ac3d72cc87c27df48d47a08301d1b8fc8
