l1Config:
    networkConfig: 0x66Cda4285693D2d015E94Ff4cf361B9E6ca6c225
    messagebus: 0x841F90a0210b6012bD202307b6eB5523b0C1a92B
    bridge: 0x852a90d4058E4E2A5f63609B9bFD0CB6c932D7Fb
    crosschain: 0x0d1486d562a71c2b4Df7D85dDEaC6F15A4b43c96
    rollup: 0x7Fc971f08E54D7D49A841b15002fBE377d05605E
    enclaveRegistry: 0xFf331Ca9D5Aa688Dc842654E780481F4A486d58c
    starthash: 0x725574e0282f5bb579f4183892c6b1b8b2a0380f506e23057c21e426c36d6c4d
