l1Config:
    networkConfig: 0xcCD676ceE303e4dE09c58e72b3F037d57FC39a84
    messagebus: 0x1C0eE612Da4Ba6Da8ed7b2cF430f5AD2E81eF654
    bridge: 0xeA65385ed9660dF5065DD036FDFdb65c4805614B
    crosschain: 0x19852474BEdF63ac4Eb361434E9A5Dd9824aa4e6
    rollup: 0x3Ec27054A4943979F236C683C5AeCDe930636328
    enclaveRegistry: 0x54be8D21041251e416C094197Cfe0221dde0CBcB
    starthash: 0x868bacac9865b60dd0cdc12ab86296e3f82260084556d70b62465d43c57fc8b2
