l1Config:
    networkConfig: 0x71EdeA5b55a1a58766f7b9211665DA81c87cF2AE
    messagebus: 0xD9006b712905E183CCf873d3696031a4Ddda4513
    bridge: 0x4Ed30A550f195D03f518CF218aBE440865323634
    crosschain: 0x5d8ae7d089294Fe079aa880B3ac4C481B2053188
    rollup: 0xDA4CD59Cb041890007796946D96e7eA4c7bd63e7
    enclaveRegistry: 0x587A8124d1aD99B2344723e9c615d9ab02be8aE9
    starthash: 0xcf5f435893f0661e168b34ce6425a995afd5143ce7b14992f669196680b7753f
