l1Config:
    networkConfig: 0xEFf07653d0e4bFeE229addA70399272Cea52d915
    messagebus: 0xE59066B60e1607F3D4B34FcF9ea572973Bb1f0dd
    bridge: 0x4D134deb051694bEAfa3AD66395736Ff0449A511
    crosschain: 0x42b0E408D729Aa49e4899F1479B038e96F650D46
    rollup: 0xda37E4383e7504889627420442E7D0CE3CA14cE2
    enclaveRegistry: 0x55141A29817b694391BE284342B25662d203606b
    starthash: 0xeabfc62a3a039e0a408661fbd70ee0f85205bd7015a49c974b54a63a052b1cde
