l1Config:
    networkConfig: 0x9e0C1A6cA9e6A33ed3d31501e33B5901F544282b
    messagebus: 0xa3cA442122bA4e3727f3b05A8889d9C7DF12be74
    bridge: 0xbD1C624A1CAfd3bD03039a6E9Bc1d46AD1635241
    crosschain: 0xB6d9F41389C7790874105CdC1ba6165016cB8097
    rollup: 0xcc6d2f3224925269724F42b9E41be0Fb99825ee2
    enclaveRegistry: 0x571542CC53eAfbFaAa210499704C9CaF2d422736
    starthash: 0x3e554206f70735d07b67f4c7364fdc55c480cfce5e353a8487d530b6c0ac19f7
