l1Config:
    networkConfig: 0x75064906ac79101FCc067d8AEf4BadAc18884e90
    messagebus: 0x84aa0f104973A8910A8A748f8AE7fC126bcA32DB
    bridge: 0xe3549D8d6F3EB1048Abe4a65210B9AC96CBa87C8
    crosschain: 0xB79bC3Ca6b5fF6B21f64D5f555ed307a861CdB94
    rollup: 0x58e14E10C99485898595dAD8D740355bA5afE1c3
    enclaveRegistry: 0x7636dFa22f4c9b2Aff2428221D904499dd00D051
    starthash: 0x57790f31d2d027ecde9fcaa6d7e840bee2acf4a7006cacca1a270e3f95fff284
