l1Config:
    networkConfig: 0xFCd93Be27d5526EB5a1BCF411A0406C94D0793Ed
    messagebus: 0x093708243c64b53c146A94929f2fB9d9659695f4
    bridge: 0x3cD1D672AC4c99c40C203Ea02D391e507b48F181
    crosschain: 0xBBBD2978f61a8e5f622287DD21c72f45C4C02514
    rollup: 0x2C6026F92D69d5a665d88a3c24B960917E99f9e2
    enclaveRegistry: 0x0d646fdcC88575d8aAc0AC78a528B7FE79b71CD9
    starthash: 0x166791c304bdd8e10d6d53a827b852a38e85c4e243cce8b001bf4c65867b861e
