l1Config:
    networkConfig: 0x0EBfaE82b5547D07CA75D36C3F005f354fe13fA0
    messagebus: 0x49F9aa2371116EcaAd291d90AF7f9B753B043EA9
    bridge: 0xCDB4e278d72463f6347A2c4200294Ea0f102b3d8
    crosschain: 0x8BB36F457e4bb94caF1742EAe3164299BDB3af3d
    rollup: 0xe9Fb04DA6deA2719a73324B1000c1eD8D20e56FA
    enclaveRegistry: 0x93aD92F80cfDCF4F883cb0a39C4dd527DdDc219b
    starthash: 0x0c7c60286b78bd77f802572c0537214557cc3cb25dea2e8fd87631752eeeed56
