l1Config:
    networkConfig: 0xA00eE65b82A30f29c849AC1ab8f73D19c73E5543
    messagebus: 0x0c2ccA7dfD1c35a6e61f5F63864a5c0155E0e2d0
    bridge: 0xeFd401E088A335D516dF4459e71461439a809064
    crosschain: 0xBDC8c0488690373659Ce8c8CD9724deeF2EB36B4
    rollup: 0xB66DF0a1bc35ABeAdbB0b3E0B4bD500C62152CA4
    enclaveRegistry: 0xd75E63146aF373d94791D5E44D2A731249BDD154
    starthash: 0x42284b47faa0a965d39d645807cb28201bc8b3aae7668725203046226ccd676f
