l1Config:
    networkConfig: 0x2160E945dAfF87D398AA5ab2bADc800aDe087807
    messagebus: 0x55D4346E36b961d574a459715971B7eC69AEdBfd
    bridge: 0x388159DF4dE914D6b60b72c7e6D177c7D60d7314
    crosschain: 0x9cbDD776645bD153288d2bb9a6c0bfFd6F67e564
    rollup: 0x2f33CB19E3a8C735348B843EdB2958A8EbCC4c9f
    enclaveRegistry: 0xE8D44FDFdb87E10bdD12a6e7687D6D2A9C2ae00B
    starthash: 0xb4c66037e09d66a34bade34941488e25424e86ecc97e6b1a6b7dc36a93c8e4f5
