l1Config:
    networkConfig: 0xC70f25f73BB63829Ff048378E3050090Dd1620cA
    messagebus: 0x66359Cf1EbFF2F495CeCB04C97AdDd1ED1055d3F
    bridge: 0x37736332fd52Cd8A775fdb443f1073988209b97F
    crosschain: 0x8c4BB678bF6e63a41f9bb604f3D9d6C841eeD974
    rollup: 0x448E5Ed217250175040E05fd88f284879383d57E
    enclaveRegistry: 0x5953972B21DcCb827fc821E90fD423a86c8D66E2
    starthash: 0x0c065c386acfa45c5f4d85ca80197bf14ed8fcad32efc49278758b3b9718e5e2
