l1Config:
    networkConfig: 0xaf83D033ea76c32a71Da772D001876eEe9B35534
    messagebus: 0xdF1C9EcCec7b6C1c0c48376f8c3b1D6a5a3b6D1E
    bridge: 0xA6d263D836BC81616f3FB1137C9B126c8250C675
    crosschain: 0xFADF6F4aebcF3d62f8aAd75458f6A1bEd41CB75f
    rollup: 0x30dCB2076dE6Dd49bb73591C363c4d7B8dbb4192
    enclaveRegistry: 0x417f5Aa24900Bb96ad8338bB52b89E07521DFea4
    starthash: 0x42758fe60b4f2eb4f4b51d1b7ea5eccd89c830149345d2a8d6bee7ca06c1e3e2
