l1Config:
    networkConfig: 0x27BAD2949F6DE9576127a4eCeCb7060BaC47649a
    messagebus: 0x3728C4ab77A15c78dC0B5feF2F74DB035927AfFe
    bridge: 0x715642C79e7D1e66165657f766906cc35F4Fe528
    crosschain: 0x987bB1a1B471360872E6bDC04ce3F9b724c68CB0
    rollup: 0x63FD8b924e25e6344e59C3e8B010dcD402a33348
    enclaveRegistry: 0xf515c4e49D97E06d73cC4Ce40fF2da05f9236Fe3
    starthash: 0x32195e23769bde531c3c11f7e215cd272a755f0fa5028640dba1437d0b57225b
