l1Config:
    networkConfig: 0x4E42d73990B5Cee9f2F1F889A55DF08317752db8
    messagebus: 0xDBf528c85e38196758969176583C6d3629403215
    bridge: 0x6a731Da3Be6A0a6C80ADC86DF295Ee6070E1E51a
    crosschain: 0x8F47925155ABf4403e6c5A013ac9BF87A2444150
    rollup: 0x0685520f7741724140dcB70F1E9faE4AE4Fc4ef6
    enclaveRegistry: 0xdA204d5D7117892F9C8F8594525680C7710299c6
    starthash: 0xe02703382347c40dfe5d3659c9d40f1dd0c88ff9c954b8eceb8bd60ebb4cfcf1
