l1Config:
    networkConfig: 0x02fBa75375b673833D2723b0AEFB4ea74E432EaE
    messagebus: 0x1dc6bF9a022a51F4B55fbE13a452f1C51ebBA493
    bridge: 0x9736DDc3DBDBc71F632aA7cFCB7c1F8374197d48
    crosschain: 0xE40a0293319E5ae8a394435358AA2081C1E18D5e
    rollup: 0x0171E4d04769BE56206CB6A9d7E5581aD3DF204c
    enclaveRegistry: 0x24C87284a6Db9C068E228bb863e789B399814f9F
    starthash: 0xed7c490f5e02650388d95b54665b3a74945593442314e32a4ae50b2f0191d3db
