l1Config:
    networkConfig: 0xAcf2052BCa3Fa77F70A9244EBE72239b62e4BE32
    messagebus: 0xFE928e4B6AB6b294138a5CCfa47920dc18C9d729
    bridge: 0x06081C95B0696F34b1530D2a99725A7862A2313e
    crosschain: 0xe10e13b81abe57Cde33F6Ab903AA0fF4a3ae8d5F
    rollup: 0xa33c2AD016d7EFc068449F2172A8658e749dA9F0
    enclaveRegistry: 0x84515EdbC4C755FF706bB15e0d1E7b0449b70eaC
    starthash: 0x9964bb68afb7b43a79d6fdf1903a99da28436330d92006f8b719b2d45609afd1
