l1Config:
    networkConfig: 0x9B294edf7F587972C0b7E853578231b7F5612D59
    messagebus: 0xe7Efa17ba4269d754c46e3F683A03141aeDdde20
    bridge: 0x61021aadC10aFE766c89c9A8ec3f08c8D274e49b
    crosschain: 0x494696571d8191276684bB5Fe620DD1EEFf75649
    rollup: 0x24EbD6a0D7090600917fd83E2E3E4b1A6cE857c6
    enclaveRegistry: 0x1Cc34390DBceA789303403776864056f4834D6EF
    starthash: 0xafa00d321cfc1dfe9c6e92bd3350f1b29bbd661a1e8aab1b7545e04d0140d7b0
