l1Config:
    networkConfig: 0xCbCC11D104167913Bd7Ec70d82a47643Aa3bC601
    messagebus: 0x48c331a19d7Cfcb31227FBA425e868885B98Cc41
    bridge: 0xEF8857CAD8463489D3688b515C8571E9f86B3cDc
    crosschain: 0xe66Bb66fA045fbF8B1ca8DD96361B6AB4a13fE39
    rollup: 0x440c84a3B9ad2d1426E8C323174Ed06364D6615b
    enclaveRegistry: 0xa9a843b79b2af59f1b7309e990D820332c2F7cbf
    starthash: 0xb6bd817602607f05a4664fc7d791b890ce0b1abedd8f2e78793ebc70eb37547f
