l1Config:
    networkConfig: 0xC531C0Bbc5BF7D1a6Bb9323d0D04186E828C803E
    messagebus: 0x4F8cEd4A902481af85458a37275F90609Ab4ac7b
    bridge: 0x5522036747bEf95B4244F508E149d10F1d7ec39A
    crosschain: 0xbe0010288B4eb7c88ED0FA42b12e9993DAB3609E
    rollup: 0x7Ed00Add3E95590ed17c7e6f892570940749C04A
    enclaveRegistry: 0xABF5056cD3CF80a038C489F3F985EaB53225014C
    starthash: 0xa2036a6354a85403f6e2b3f1c7515d9172d56f56c13369e2fcc52f23a29128b3
