l1Config:
    networkConfig: 0x1639020CfdD3cd8f4d0f3e8EA829560CAc4cDe0B
    messagebus: 0xe1d6C91718d33b5b18530231615f5e371613f918
    bridge: 0x29CcF334aa4CB6e100D2eC8964Cb1C9453B111e3
    crosschain: 0x025a7E022a031453536992d23739Bf1C46D38B97
    rollup: 0x36a6Cf3F16A13988188a1F67Fd9f51D280ab92D6
    enclaveRegistry: 0x08eD132E975Ac369CA1F5e5A9978F74c7f8316CD
    starthash: 0xecd2b8f648c08bfa1af26dc21030909febef1f658a0d9ea841cad327a5ab29ca
