l1Config:
    networkConfig: 0x60A5fB8Ef2706e99682a28423DF86BE282e785Fc
    messagebus: 0x0E3A9370a30ccC9608fc855C6eA1DD6Fb5C805dB
    bridge: 0x4CE0F5517D867624fde983e95290133Df4C7921E
    crosschain: 0x19834FdFaba4D18C625F07D1B44aC7717941c59e
    rollup: 0x5c356d6D836C95943147fCd4A34212179914d0F8
    enclaveRegistry: 0xE5feA54b632Fea462103d47743aBf6C21C52BFDd
    starthash: 0x2cd8d4368cd50e00d30b796f173eef4722c341c34464be207626f34ef5600b40
