l1Config:
    networkConfig: 0x7cb19bD89001279cd339f78D56E61F14cB594F76
    messagebus: 0x08AFB1e43b300108f244D7DdcFDBb89787bDC4C6
    bridge: 0x781996FA06a6547D2B53d66b7070cE037b5EfF66
    crosschain: 0xc657b12a1510F2760f86387537d7c0a29D51C864
    rollup: 0x6d051b3C3C0E319A698f29A88075628245B5E62E
    enclaveRegistry: 0x9dd56299783D22Fd9128D08299374Ee19A7Ca939
    starthash: 0x94b557aeff7bca98829128666a8ac1f1902ce28880792f2665d2c3ad3f8a0855
