l1Config:
    networkConfig: 0x462a7dD43241F3ea27Da8BE93664C6B67D40636F
    messagebus: 0xC35EB9929FF8d8b9713Cc2F95d1C1aEBb3AC5038
    bridge: 0x16131B25628a7cBB0cbcF6ab6Ac308a999E8A29A
    crosschain: 0x8121e9ffE0D3F552fF956f3A8F42531B988ed4DA
    rollup: 0xe27a70A057b1f33cf2674610b0E7EF8ef0F549E7
    enclaveRegistry: 0x37BD5C93ED74Ee788a54E8f1dB4Cd84391ed1E41
    starthash: 0xe8ea9bbe2f187cb102501f86c73e09c8e52100746b6701f4067e1605a9eb60fc
