l1Config:
    networkConfig: 0x680ce7a76422125445fE0461C162D38526172a2f
    messagebus: 0x29d2997c18935D68eDb81d43521fB2e7B08c9F8a
    bridge: 0x01f02D0676057a63144932376539EfF2E8c7C7cB
    crosschain: 0xb908e99C18e2509742ae340Afb433de9c0f2334c
    rollup: 0x471F728cf4269942574A9CB60EB764acEafB08b9
    enclaveRegistry: 0x8Dc411eFE90e327AdAdcc30C42a5F174abE230B2
    starthash: 0xbc39d4a7c2124d8ba616cd9618c14cf25a41be5471fb53ee6044492312b3aed8
