l1Config:
    networkConfig: 0x618001cd3508E64838f513004DeD556F1c2a075B
    messagebus: 0xD084Af4C4B01fd57b925764c2A300faF1559a750
    bridge: 0xd5045602858840BdD15c672589bECE09751A5f97
    crosschain: 0x6b4744c34263927dB92830128b33d58563DFbfAE
    rollup: 0x7444a10B72254f3F4C46e57df791d14F2662E195
    enclaveRegistry: 0xc80138E9EC292C1a34E72Fd5123a2f155edEDed0
    starthash: 0xa5a1a3ad97c21e56467bb8b551a6e255dfb18bd5992ae8f3aa45b2d1648f84c4
