l1Config:
    networkConfig: 0x4C2375E8b4055e865BF1eaf88E0be402fa3128A9
    messagebus: 0x68Dc4e5FFce9F75ef16B886ca222E6B684E15332
    bridge: 0x5ABaF0C988ddef217e3F765C9C7ddB423dD650CE
    crosschain: 0xb2fE92D7D0aB6E78213641D10C14e3c221dA2969
    rollup: 0xBfC508D5b74E307f8Ec76128a583629C04531B14
    enclaveRegistry: 0xeEd9c0666e12Aa54017154bD219a553D86c7EcFd
    starthash: 0xf4663dd6d16fa8985ce3c827982200444b49309e9ce84fc1b8b4ec2a160454ba
