l1Config:
    networkConfig: 0x33a8159d7bb71C570ba570C01284BB83126e79Dc
    messagebus: 0x62278713aa6D5727519A02107E40a357CF980D1F
    bridge: 0xa49848465062D9A9867885c4414344630B64757F
    crosschain: 0x061A408A6c88619546a0C4c617760A9B66af45E4
    rollup: 0x1e6154d7b0e58f697c5B2E1538343F302Ba0871E
    enclaveRegistry: 0x8F16034b096d17C1B2f6E0d4FD467A4fb23F3e54
    starthash: 0x1c9aacabe02b598cf625a9476a3507345b7b7280fb8f5036e739345a724c28db
