l1Config:
    networkConfig: 0xfF7CAE5b38d36c251D938bCDE64E891DcBB63617
    messagebus: 0x78870d5d6EcBF5e98C8F35c815dE6f11B63efF3e
    bridge: 0x4E5cC154447b458Cb7903973a504Cc200a736F9A
    crosschain: 0xb527091F63c410D214961cC13804b2e01d915282
    rollup: 0x327cBcfc48d429cF92481F7C88f5042382808E18
    enclaveRegistry: 0x1102929cf2B2d5a279509ef08Ca1F1D20f9c87C6
    starthash: 0x90c624876f9f01099da0a3f969d2eb3c80f8ca41bf15d22e14e1fc8ad05dd457
