l1Config:
    networkConfig: 0xfe821EF76572751285F95F37a568c09406334c19
    messagebus: 0x92e69E4832f2dC6C62D3C0D7110B6FA3326E6EC9
    bridge: 0xd7b4e13Ce7492B5cEF102220E6Bd4e3510cD9d91
    crosschain: 0xBD21F9075469E00d75F4dAFd704308C532d1A119
    rollup: 0x53D7C31aC58C03dFD5cc09938ACA76e7a4DC9C6B
    enclaveRegistry: 0x236629674Fd567e889e47d7AA7e4e8F57BD54bED
    starthash: 0x2ea3c9b800c4ced35c1f7e23b22ec0f80a6e836ac4196b4cd4450940868f1f6e
