l1Config:
    networkConfig: 0xbD4BA5c177A1Df2cAcAB42A9537Db5e11DD282AC
    messagebus: 0x5e6C469caE4fA6876AD6D345a5a3e47B048fD9C1
    bridge: 0x0B885d008018714699Cfca4c3CAcD1EE75536112
    crosschain: 0xf9B4d0b0D43B83AD69A5ed4f1E57B5B583aD45E4
    rollup: 0x3e17bBF7F937e09AcAb651056945719D51e3023F
    enclaveRegistry: 0x88D503358Fd9Ff2b5d38D4A67651C0e26658Cd08
    starthash: 0xebd2ac61beb33bc64dcabd2e1e461ac205576a06ac05085c516ceaa2fbedfc74
