l1Config:
    networkConfig: 0xA5d342a7EBbe778C402C9AFcEb9C95486578c67A
    messagebus: 0xa289278537755E7c33aeD5EA30648689f3F06267
    bridge: 0x03c1399e09d6736cd6f4B2BBC5dbC0b77447971F
    crosschain: 0x97b801f337b1FB6362fE917b2374bBF884a98B2D
    rollup: 0xdA98D3935F1e71B343d138Ffb729f2013491572B
    enclaveRegistry: 0x8CF2D7fc563088e6B76F8547077C0beb7f011835
    starthash: 0xf02aa3494eb172f843966798ec7b45b6b03233d36d050e9cdcc5d39b4b1352fd
