l1Config:
    networkConfig: 0x2B72978312fdCba9374A7794F13fD8ab33DcA4F5
    messagebus: 0x31d4031e40318F2707531690Cd9d7F248c05c82f
    bridge: 0xbb29F86fe7624DE59D5A8533Af5f0674441cD801
    crosschain: 0x8778394b6B902f5b48a89F80E5Ea118610b28F37
    rollup: 0x2794157D8a726E02247CbA87a8c0dEdD5Dd1dC31
    enclaveRegistry: 0x28b36Ae3485fFD24524c34B41F1aD6Dfb719c847
    starthash: 0xafa131dc333d6cb6d30d3c5e1015a3e6f900139e174afa67892d02c6d4dcf784
