l1Config:
    networkConfig: 0xA058b4438D552E76046ad69c2f1520f17e868c2D
    messagebus: 0xF858D2EAc69456ab57Cea14C667bFf2501F6BCb4
    bridge: 0x17Db6C795032973e11c097b29f487C9b2D5A93C4
    crosschain: 0xA43a97Db7863090D760dBe6a57627092Ad1F76F6
    rollup: 0x3813a50B04f91C0736425D83FF63f64817b7a8E9
    enclaveRegistry: 0x9d7BdD8e7B847bC3445512A51B24eDaaa40962f8
    starthash: 0xec4314877df28953b5d30ace98e42b631c82e088dc9066dd6bb16881ab1a43ce
