l1Config:
    networkConfig: 0xE5e7717AE5EB155d0f558489fC6f984827051bb0
    messagebus: 0xD0919b961EDc71796c42b4CbB191f89bEfEa32F0
    bridge: 0xB085738E11035b90A4151207AEA138dDf168BEd3
    crosschain: 0xDF0baa33f6023e098fF023fcE5dada8e269A8A70
    rollup: 0x6363550e8497DE683220909e26C90F9f2190fda5
    enclaveRegistry: 0xC2FB9fBC6f4106bA41314FECedB6C6382Ed73223
    starthash: 0xc02310b0c9d29829ffb0ddeb61e31fbac554adc9206af3f4bb7c4f8a0cb78605
