l1Config:
    networkConfig: 0x00d5AFA76a5f903e1dE47799FEdcD8809b0736b5
    messagebus: 0xaC741779Da0483D43540Dded074CBc32D81eafaf
    bridge: 0x343EDfBaF0B67744F8b337438016B50D8459ADA5
    crosschain: 0x3f81ae7c23978E9ae2789E4ecA8391c51B04EA91
    rollup: 0x7B2A713ab0246ffc0C71C6E8e5342E9413986554
    enclaveRegistry: 0xB869d4E8Fe02E94e60522D3c65Df10d5D0D3396B
    starthash: 0xd88226119e179a97a3cc24efd28f086c9482c5df246c9be636f88b173df44361
