l1Config:
    networkConfig: 0x04a65183e532743A97406DB52e2412df295109ae
    messagebus: 0xB8b0A947c6CFcc3D59a34761A7178a6A067c6dFD
    bridge: 0x6c661f529d97b9c7aB3eca30db7D6Afb7e079A32
    crosschain: 0x0991122C718DD4F6C4EB8a0D1119629D46778198
    rollup: 0x1A0eC86c6A4Dd5f99B41Ff3b41313e4A3EaC269c
    enclaveRegistry: 0xE4c937aDa3e170d8170132299519A2EDc5927479
    starthash: 0xd744b74818206524472c18e7997662d25a90deb484387a65048762b7c034ed71
