l1Config:
    networkConfig: 0x3Bf9f5CD8B42892697710c3E55f986103Ad8FDa7
    messagebus: 0xd1a9f987479985f0529d7B1ab70Aa0150F9e4CBC
    bridge: 0x5fb05bEddb8A8aB8F4e7628571767219a857fD4f
    crosschain: 0x3E573A67c7ddC1314Ed3433dd5D635D05509b11d
    rollup: 0x9b73E86dE5422A103d3b836a2F91462d029Fd936
    enclaveRegistry: 0x4b9d7a1e9A0e7BA0eB7daa6C2941952A1aFC4C71
    starthash: 0xf3693ce580e440e1e4aacd8aba4af822f4a4e88af6a437e4278f87cc15faedfc
