l1Config:
    networkConfig: 0xF743FCaF0d6cBC5c1853CBdAAC09Db65e3C454BA
    messagebus: 0x5e9C43D61F7c85e49dbeb95d48ab5b6B3c263dC2
    bridge: 0xB1C2e62CFE5105d2E85b9C7f9532b85E5a5E3491
    crosschain: 0xf5C043ee8826F71A468eee7462B32f92917e388c
    rollup: 0xd79A3601b51F90Aea14B5d31Cfeef8bA2B947848
    enclaveRegistry: 0x46C87C2E18Cf21fD8E23247BbfC3a8AF675e7DF6
    starthash: 0x0b41b43c4dd9bc0515d37db34d315648faebde79d7337d25ec0be3a36c26414f
