l1Config:
    networkConfig: 0xDbbC5eb1483f24DDD40C12f30489950fa32A5CA5
    messagebus: 0x8f866E1C3Ac2C92b873A8df600E17C6FC7948F2A
    bridge: 0xA786333ef134CC54aCCA6E6C1b19c25eED096DD2
    crosschain: 0xB55016926333063a3E26181136Af419510Cedc57
    rollup: 0x416cc10cb71BB905064004b3861e2DE3699fC8F8
    enclaveRegistry: 0x8D288BF41dD7B5d63bAD48f20CA4e31229a841C9
    starthash: 0x256d3298461e9ea412904b026d495d09c78391004a8305870cc58bf003dab1f0
