l1Config:
    networkConfig: 0x699267d8e7D472090596e5794AFA1b5049Ad3Fc2
    messagebus: 0xdf251B180d2e5edd82dE627Fe1Eb1bb0bCbC4344
    bridge: 0x266cccE79918d78D74759ea0db4C4B50fFf718c0
    crosschain: 0xECBCa9393c8e099e80aA2498Ae5eB31769fa3eB3
    rollup: 0x31807EBc890De3C8b4bE6fD0F8a198cf03d98634
    enclaveRegistry: 0x96a0AD804590EA98a65a9836D8414017A3bE92A0
    starthash: 0x81bd0f16c39f5d61eaedc7eb019ed9ec16297aca4b045dcdbeda7fb592ec3eba
