nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

faucet:
  replicaCount: 1
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/faucet_sepolia_testnet
    tag: latest
  nodeHost: "tn-rpc.ten.xyz"
  nodePort: "443"
  pk: "YOUR_FAUCET_PRIVATE_KEY"
  jwtSecret: "YOUR_JWT_SECRET"
  chainID: 8443
  host: "tn-faucet.ten.xyz"

tenscan:
  api:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/api_obscuro_scan_sepolia_testnet
      tag: latest
    nodeHostAddress: "https://tn-rpc.ten.xyz"
    host: "tn-api.tenscan.io"

  fe:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/fe_obscuro_scan_sepolia_testnet
      tag: latest
    env:
      apiHost: "https://tn-api.tenscan.io"
      version: "v1.0.0"
      environment: "testnet"
    host: "tn.tenscan.io"
    host2: "tn.tenscan.io"
bridge:
  frontend:
    enabled: true
    image:
      repository: "testnetobscuronet.azurecr.io/obscuronet/fe_bridge_sepolia_testnet"
      tag: "latest"
      pullPolicy: Always
    containerPort: 80
    service:
      port: 80
    host: "tn-bridge.ten.xyz"
    env:
      apiHost: "https://tn-rpc.ten.xyz/v1"
    # You can add other environment variables here

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
