nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

faucet:
  replicaCount: 1
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/faucet_testnet
    tag: latest
  nodeHost: "erpc.testnet.ten.xyz"
  nodePort: "80"
  pk: "YOUR_FAUCET_PRIVATE_KEY"
  jwtSecret: "YOUR_JWT_SECRET"
  chainID: 8443
  host: "testnet-faucet.ten.xyz"

tenscan:
  api:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/api_obscuro_scan_testnet
      tag: latest
    nodeHostAddress: "http://erpc.testnet.ten.xyz:80"
    host: "testnet-api.tenscan.io"

  fe:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/fe_obscuro_scan_testnet
      tag: latest
    env:
      apiHost: "https://testnet-api.tenscan.io"
      version: "v1.0.0"
      environment: "testnet"
    host: "testnet.tenscan.io"
    host2: "testnet.tenscan.io"
bridge:
  frontend:
    enabled: true
    image:
      repository: "testnetobscuronet.azurecr.io/obscuronet/fe_bridge_testnet"
      tag: "latest"
      pullPolicy: Always
    containerPort: 80
    service:
      port: 80
    host: "testnet-bridge.ten.xyz"
    env:
      apiHost: "https://testnet-rpc.ten.xyz/v1"
    # You can add other environment variables here

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
